app = "earnings-bot-empty-grass-2395"
primary_region = "iad"

auto_stop_machines = "false"

[build]
  strategy = "docker"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"

[[services]]
  auto_stop_machines = "off"
  auto_start_machines = true

[mounts]
  source = "botdata"
  destination = "/data"
