

ALPACA_SECRET_KEY = '7TEJhUKXpQPJW9bjuN7WoMZqLPmfkx6i2Gqpa64U'
ALPACA_KEY = 'PK94C6N1YEYXDPL30FAB'
MARKET_URL = "https://paper-api.alpaca.markets/v2"

header = {
    "APCA-API-KEY-ID": ALPACA_KEY,
    "APCA-API-SECRET-KEY": ALPACA_SECRET_KEY,
}
